# Generated by Django 3.2.6 on 2022-02-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('university', models.CharField(choices=[('Leading', 'Leading'), ('Dhaka University', 'Dhaka University'), ('North South', 'North South'), ('Rajshahi', 'Rajshahi')], default='CSE', max_length=200)),
                ('departMent', models.CharField(choices=[('CSE', 'CSE'), ('ENGLISH', 'ENGLISH'), ('BBA', 'BBA'), ('BANGLA', 'BANGLA'), ('ISLAMIC STUDIES', 'ISLAMIC STUDIES'), ('EEE', 'EEE')], default='CSE', max_length=200)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
    ]
