# Generated by Django 3.2.6 on 2022-02-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reditapp', '0002_sharefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharefile',
            name='semister',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=200),
        ),
    ]
