# Generated by Django 3.2.6 on 2022-02-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reditapp', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharefile',
            name='university',
            field=models.CharField(choices=[('Leading', 'Leading'), ('Dhaka University', 'Dhaka University'), ('North South', 'North South'), ('Rajshahi', 'Rajshahi')], default='Leading', max_length=200),
        ),
    ]
