# Generated by Django 3.2.6 on 2022-02-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reditapp', '0005_sharefile_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharefile',
            name='isthattrue',
            field=models.BooleanField(default=False),
        ),
    ]
