# Generated by Django 3.2.6 on 2022-02-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reditapp', '0006_sharefile_isthattrue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mypost', models.TextField(blank=True)),
                ('postimage', models.ImageField(upload_to='uploadpost/')),
                ('postfile', models.FileField(upload_to='uploadfile/')),
                ('likes', models.ManyToManyField(related_name='post_likes', to='reditapp.Registration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reditapp.registration')),
                ('views', models.ManyToManyField(related_name='post_views', to='reditapp.Registration')),
            ],
        ),
    ]
