# Generated by Django 3.2.6 on 2022-02-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reditapp', '0007_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postfile',
            field=models.FileField(blank=True, null=True, upload_to='uploadfile/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ImageField(blank=True, null=True, upload_to='uploadpost/'),
        ),
    ]
