# Generated by Django 3.2.6 on 2022-02-20 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reditapp', '0009_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='myprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reditapp.userprofile'),
        ),
    ]
