# Generated by Django 3.2.6 on 2022-02-20 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reditapp', '0010_post_myprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 2, 20, 21, 4, 4, 54300))),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reditapp.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reditapp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reditapp.registration')),
            ],
        ),
    ]
