# Generated by Django 3.2.6 on 2022-03-03 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reditapp', '0012_alter_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 13, 12, 56, 205037)),
        ),
    ]
